### ISSUE TITLE
Admin Product Labels UI not provided

### ISSUE THREAD

**Issue by Loocos** [tavy315/SyliusLabelsPlugin#1]
Hi,

I just installed it, no problem, only one thing.
I don't have the label menu panel in the product form : 
https://github.com/tavy315/SyliusLabelsPlugin/raw/master/docs/images/admin-product-labels.png

I saw in your code than you're using event listener to add the menu item dynamically.
Maybe because I'm running on Sylius 1.8+

**Comment by tavy315** [comment]
Hi @Loocos ,

Sorry for this delayed answer, I never saw this issue until now. 

Using an [event listener](https://github.com/tavy315/SyliusLabelsPlugin/blob/master/src/Menu/AdminProductFormMenuListener.php) is the only way to customize menus in Sylius, you can check their [documentation](https://docs.sylius.com/en/latest/customization/menu.html).
